/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ModemRouteImport } from './routes/modem'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForwardingRouteImport } from './routes/forwarding'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as IndexRouteImport } from './routes/index'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ModemRoute = ModemRouteImport.update({
  id: '/modem',
  path: '/modem',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForwardingRoute = ForwardingRouteImport.update({
  id: '/forwarding',
  path: '/forwarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/favorites': typeof FavoritesRoute
  '/forwarding': typeof ForwardingRoute
  '/login': typeof LoginRoute
  '/modem': typeof ModemRoute
  '/status': typeof StatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/favorites': typeof FavoritesRoute
  '/forwarding': typeof ForwardingRoute
  '/login': typeof LoginRoute
  '/modem': typeof ModemRoute
  '/status': typeof StatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/favorites': typeof FavoritesRoute
  '/forwarding': typeof ForwardingRoute
  '/login': typeof LoginRoute
  '/modem': typeof ModemRoute
  '/status': typeof StatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/favorites'
    | '/forwarding'
    | '/login'
    | '/modem'
    | '/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config'
    | '/favorites'
    | '/forwarding'
    | '/login'
    | '/modem'
    | '/status'
  id:
    | '__root__'
    | '/'
    | '/config'
    | '/favorites'
    | '/forwarding'
    | '/login'
    | '/modem'
    | '/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRoute
  FavoritesRoute: typeof FavoritesRoute
  ForwardingRoute: typeof ForwardingRoute
  LoginRoute: typeof LoginRoute
  ModemRoute: typeof ModemRoute
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modem': {
      id: '/modem'
      path: '/modem'
      fullPath: '/modem'
      preLoaderRoute: typeof ModemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forwarding': {
      id: '/forwarding'
      path: '/forwarding'
      fullPath: '/forwarding'
      preLoaderRoute: typeof ForwardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRoute,
  FavoritesRoute: FavoritesRoute,
  ForwardingRoute: ForwardingRoute,
  LoginRoute: LoginRoute,
  ModemRoute: ModemRoute,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
