/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModemRouteImport } from './routes/modem'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForwardingRouteImport } from './routes/forwarding'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as IndexRouteImport } from './routes/index'

const ModemRoute = ModemRouteImport.update({
  id: '/modem',
  path: '/modem',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForwardingRoute = ForwardingRouteImport.update({
  id: '/forwarding',
  path: '/forwarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/forwarding': typeof ForwardingRoute
  '/login': typeof LoginRoute
  '/modem': typeof ModemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/forwarding': typeof ForwardingRoute
  '/login': typeof LoginRoute
  '/modem': typeof ModemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/forwarding': typeof ForwardingRoute
  '/login': typeof LoginRoute
  '/modem': typeof ModemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/config' | '/forwarding' | '/login' | '/modem'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/config' | '/forwarding' | '/login' | '/modem'
  id: '__root__' | '/' | '/config' | '/forwarding' | '/login' | '/modem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRoute
  ForwardingRoute: typeof ForwardingRoute
  LoginRoute: typeof LoginRoute
  ModemRoute: typeof ModemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/modem': {
      id: '/modem'
      path: '/modem'
      fullPath: '/modem'
      preLoaderRoute: typeof ModemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forwarding': {
      id: '/forwarding'
      path: '/forwarding'
      fullPath: '/forwarding'
      preLoaderRoute: typeof ForwardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRoute,
  ForwardingRoute: ForwardingRoute,
  LoginRoute: LoginRoute,
  ModemRoute: ModemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
